"""
Base Strategy Class
Abstract base for all trading strategies

TIME-AWARE: Targets are automatically adjusted based on time remaining until 3:15 PM square-off
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List
from datetime import datetime, time
from dataclasses import dataclass
from enum import Enum
import pandas as pd
from loguru import logger


def get_intraday_time_multiplier() -> float:
    """
    Get target multiplier based on time remaining until 3:15 PM square-off
    
    Returns:
        float: Multiplier to apply to targets (0.0 to 1.0)
    """
    now = datetime.now()
    current_mins = now.hour * 60 + now.minute
    
    market_open = 9 * 60 + 15   # 9:15 AM
    squareoff = 15 * 60 + 15    # 3:15 PM
    
    if current_mins < market_open:
        return 1.0  # Pre-market
    elif current_mins >= squareoff:
        return 0.0  # Square-off time
    elif current_mins >= 15 * 60:  # After 3:00 PM
        return 0.3
    elif current_mins >= 14 * 60 + 30:  # After 2:30 PM
        return 0.5
    elif current_mins >= 14 * 60:  # After 2:00 PM
        return 0.7
    elif current_mins >= 12 * 60:  # After 12:00 PM
        return 0.9
    elif current_mins >= 10 * 60:  # After 10:00 AM - Prime time
        return 1.0
    else:  # 9:15 - 10:00 AM - Opening
        return 0.8


class SignalType(Enum):
    STRONG_BUY = "strong_buy"
    BUY = "buy"
    HOLD = "hold"
    SELL = "sell"
    STRONG_SELL = "strong_sell"


@dataclass
class Signal:
    """Trading signal generated by a strategy"""
    signal_type: SignalType
    symbol: str
    strength: float  # 0.0 to 1.0
    price: float
    stoploss: float
    target: float
    quantity: int
    reason: str
    timestamp: datetime
    metadata: Dict[str, Any] = None
    
    @property
    def is_buy(self) -> bool:
        return self.signal_type in [SignalType.BUY, SignalType.STRONG_BUY]
    
    @property
    def is_sell(self) -> bool:
        return self.signal_type in [SignalType.SELL, SignalType.STRONG_SELL]


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies
    
    Subclasses must implement:
    - name: Strategy name
    - analyze(): Generate trading signals
    - should_exit(): Check exit conditions
    """
    
    def __init__(
        self,
        market_data,
        risk_manager,
        symbols: List[str],
        exchange: str = "NSE",
        timeframe: str = "5min",
        start_time: str = "09:20",
        end_time: str = "15:00"
    ):
        self.market_data = market_data
        self.risk_manager = risk_manager
        self.symbols = symbols
        self.exchange = exchange
        self.timeframe = timeframe
        self.start_time = datetime.strptime(start_time, "%H:%M").time()
        self.end_time = datetime.strptime(end_time, "%H:%M").time()
        
        self._is_active = False
        self._signals_generated: List[Signal] = []
        
    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name"""
        pass
    
    @property
    def is_trading_hours(self) -> bool:
        """Check if current time is within trading hours"""
        now = datetime.now().time()
        return self.start_time <= now <= self.end_time
    
    @property
    def is_active(self) -> bool:
        return self._is_active and self.is_trading_hours
    
    def activate(self) -> None:
        """Activate the strategy"""
        self._is_active = True
        logger.info(f"Strategy '{self.name}' activated")
    
    def deactivate(self) -> None:
        """Deactivate the strategy"""
        self._is_active = False
        logger.info(f"Strategy '{self.name}' deactivated")
    
    @abstractmethod
    def analyze(self, symbol: str, data: pd.DataFrame) -> Optional[Signal]:
        """
        Analyze market data and generate trading signal
        
        Args:
            symbol: Trading symbol
            data: OHLCV DataFrame with indicators
            
        Returns:
            Signal object if conditions are met, None otherwise
        """
        pass
    
    @abstractmethod
    def should_exit(self, symbol: str, position: Dict[str, Any], data: pd.DataFrame) -> Optional[Signal]:
        """
        Check if an existing position should be exited
        
        Args:
            symbol: Trading symbol
            position: Current position data
            data: OHLCV DataFrame with indicators
            
        Returns:
            Exit signal if position should be closed, None otherwise
        """
        pass
    
    def calculate_stoploss(self, price: float, data: pd.DataFrame) -> float:
        """Calculate stop-loss price based on strategy rules"""
        sl_pct = self.risk_manager.config.default_stoploss_pct
        return price * (1 - sl_pct / 100)
    
    def calculate_target(self, price: float, stoploss: float) -> float:
        """
        Calculate target price based on risk-reward ratio
        
        TIME-AWARE: Targets are reduced late in the trading day to ensure
        they can be achieved before 3:15 PM square-off
        """
        risk = price - stoploss
        target_pct = self.risk_manager.config.default_target_pct
        base_target = price + (price * target_pct / 100)
        
        # Apply time multiplier to reduce targets late in day
        time_multiplier = get_intraday_time_multiplier()
        adjusted_target = price + (base_target - price) * time_multiplier
        
        return adjusted_target
    
    def calculate_quantity(self, symbol: str, price: float, stoploss: float) -> int:
        """Calculate position size based on risk"""
        sl_pct = abs((price - stoploss) / price) * 100 if price > 0 else 1.5
        quantity, _ = self.risk_manager.calculate_position_size(
            symbol=symbol,
            price=price,
            stoploss_pct=sl_pct
        )
        return quantity
    
    def run(self) -> List[Signal]:
        """
        Run strategy on all symbols
        
        Returns:
            List of generated signals
        """
        if not self.is_active:
            return []
        
        # Check if market_data is available
        if self.market_data is None:
            # Only log once per minute to avoid log flooding
            if not hasattr(self, '_last_no_data_warning') or \
               (datetime.now() - self._last_no_data_warning).seconds > 60:
                logger.warning(f"{self.name}: Market data provider not initialized - skipping analysis")
                self._last_no_data_warning = datetime.now()
            return []
        
        signals = []
        symbols_with_no_data = []
        
        for symbol in self.symbols:
            try:
                # Get market data with indicators
                ohlc = self.market_data.get_ohlc(symbol, self.exchange)
                if not ohlc:
                    symbols_with_no_data.append(symbol)
                    continue
                
                # Create DataFrame (in real scenario, you'd have historical data)
                df = pd.DataFrame([ohlc])
                df = self.market_data.calculate_indicators(df)
                
                # Check for existing position
                if symbol in self.risk_manager.open_positions:
                    position = self.risk_manager.open_positions[symbol]
                    exit_signal = self.should_exit(symbol, position, df)
                    if exit_signal:
                        signals.append(exit_signal)
                        self._signals_generated.append(exit_signal)
                else:
                    # Look for entry signal
                    entry_signal = self.analyze(symbol, df)
                    if entry_signal:
                        signals.append(entry_signal)
                        self._signals_generated.append(entry_signal)
                        
            except Exception as e:
                logger.error(f"Error analyzing {symbol}: {e}")
        
        # Log summary if many symbols had no data (only once per minute)
        if symbols_with_no_data:
            if not hasattr(self, '_last_no_data_summary') or \
               (datetime.now() - self._last_no_data_summary).seconds > 60:
                logger.debug(f"{self.name}: No data for {len(symbols_with_no_data)}/{len(self.symbols)} symbols")
                self._last_no_data_summary = datetime.now()
        
        return signals
    
    def get_stats(self) -> Dict[str, Any]:
        """Get strategy statistics"""
        buy_signals = sum(1 for s in self._signals_generated if s.is_buy)
        sell_signals = sum(1 for s in self._signals_generated if s.is_sell)
        
        return {
            "name": self.name,
            "is_active": self._is_active,
            "symbols": self.symbols,
            "total_signals": len(self._signals_generated),
            "buy_signals": buy_signals,
            "sell_signals": sell_signals
        }
